//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Back_End.ModelsBD
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BackEndEntities : DbContext
    {
        public BackEndEntities()
            : base("name=BackEndEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CAP_Corte> CAP_Corte { get; set; }
        public virtual DbSet<CAP_CorteDetalle> CAP_CorteDetalle { get; set; }
        public virtual DbSet<CAP_MovimientosCuenta> CAP_MovimientosCuenta { get; set; }
        public virtual DbSet<CAP_SolicitudPrestamo> CAP_SolicitudPrestamo { get; set; }
        public virtual DbSet<CAT_CategoriasGasto> CAT_CategoriasGasto { get; set; }
        public virtual DbSet<CAT_Cuentas> CAT_Cuentas { get; set; }
        public virtual DbSet<CAT_Departamentos> CAT_Departamentos { get; set; }
        public virtual DbSet<CAT_Empleados> CAT_Empleados { get; set; }
        public virtual DbSet<CAT_EmpleadosArchivos> CAT_EmpleadosArchivos { get; set; }
        public virtual DbSet<CAT_Navegador> CAT_Navegador { get; set; }
        public virtual DbSet<CAT_PermisoUsuario> CAT_PermisoUsuario { get; set; }
        public virtual DbSet<CAT_Puestos> CAT_Puestos { get; set; }
        public virtual DbSet<CAT_Roles> CAT_Roles { get; set; }
        public virtual DbSet<CAT_RubrosPrestamos> CAT_RubrosPrestamos { get; set; }
        public virtual DbSet<CAT_TabuladorAguinaldo> CAT_TabuladorAguinaldo { get; set; }
        public virtual DbSet<CAT_TabuladorPrimaVacacional> CAT_TabuladorPrimaVacacional { get; set; }
        public virtual DbSet<CAT_TipoMovimiento> CAT_TipoMovimiento { get; set; }
        public virtual DbSet<CAT_Usuarios> CAT_Usuarios { get; set; }
        public virtual DbSet<CFG_Configuracion> CFG_Configuracion { get; set; }
        public virtual DbSet<LOG_RecuperarPassword> LOG_RecuperarPassword { get; set; }
        public virtual DbSet<LOG_Sesiones> LOG_Sesiones { get; set; }
        public virtual DbSet<CAT_Puestos_respaldo> CAT_Puestos_respaldo { get; set; }
    }
}
