//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Back_End.ModelsBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAP_Corte
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CAP_Corte()
        {
            this.CorteDetalle = new HashSet<CAP_CorteDetalle>();
            this.CAP_MovimientosCuenta = new HashSet<CAP_MovimientosCuenta>();
        }
    
        public int nIdCorte { get; set; }
        public int nIdRubro { get; set; }
        public System.DateTime dFechaCorte { get; set; }
        public decimal nTotal { get; set; }
        public bool bPagado { get; set; }
        public bool bActivo { get; set; }
        public string cUsuario_Registro { get; set; }
        public System.DateTime dFecha_Registro { get; set; }
        public string cUsuario_UltimaModificacion { get; set; }
        public System.DateTime dFecha_UltimaModificacion { get; set; }
        public string cUsuario_Eliminacion { get; set; }
        public Nullable<System.DateTime> dFecha_Eliminacion { get; set; }
        public short nVersion { get; set; }
    
        public virtual CAT_RubrosPrestamos Rubro { get; set; }
        public virtual CAT_Usuarios CAT_Usuarios { get; set; }
        public virtual CAT_Usuarios CAT_Usuarios1 { get; set; }
        public virtual CAT_Usuarios CAT_Usuarios2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CAP_CorteDetalle> CorteDetalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CAP_MovimientosCuenta> CAP_MovimientosCuenta { get; set; }
    }
}
