//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Back_End.ModelsBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAP_MovimientosCuenta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CAP_MovimientosCuenta()
        {
            this.MovimientosCuentaCancela = new HashSet<CAP_MovimientosCuenta>();
        }
    
        public int nIdMovimiento { get; set; }
        public int nIdCuenta { get; set; }
        public int nIdTipoMovimiento { get; set; }
        public int nIdCategoria { get; set; }
        public Nullable<int> nIdCorte { get; set; }
        public Nullable<int> nIdPrestamo { get; set; }
        public Nullable<int> nIdMovimientoCancela { get; set; }
        public decimal nImporte { get; set; }
        public string cObservaciones { get; set; }
        public string cRutaDocumento { get; set; }
        public bool bActivo { get; set; }
        public string cUsuario_Registro { get; set; }
        public System.DateTime dFecha_Registro { get; set; }
        public string cUsuario_Eliminacion { get; set; }
        public Nullable<System.DateTime> dFecha_Eliminacion { get; set; }
    
        public virtual CAP_Corte Corte { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CAP_MovimientosCuenta> MovimientosCuentaCancela { get; set; }
        public virtual CAP_MovimientosCuenta MovimientoCuentaCancela { get; set; }
        public virtual CAP_SolicitudPrestamo CAP_SolicitudPrestamo { get; set; }
        public virtual CAT_CategoriasGasto CategoriaGasto { get; set; }
        public virtual CAT_Cuentas Cuenta { get; set; }
        public virtual CAT_TipoMovimiento TipoMovimiento { get; set; }
    }
}
