//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Back_End.ModelsBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT_EmpleadosArchivos
    {
        public int nIdArchivoEmpleado { get; set; }
        public int nCodEmpleado { get; set; }
        public string cRutaArchivo { get; set; }
        public string cNombre { get; set; }
        public bool bActivo { get; set; }
        public string cUsuario_Registro { get; set; }
        public System.DateTime dFecha_Registro { get; set; }
        public string cUsuario_Eliminacion { get; set; }
        public Nullable<System.DateTime> dFecha_Eliminacion { get; set; }
    
        public virtual CAT_Empleados CAT_Empleados { get; set; }
        public virtual CAT_Usuarios CAT_Usuarios { get; set; }
        public virtual CAT_Usuarios CAT_Usuarios1 { get; set; }
    }
}
