//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Back_End.ModelsBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT_Navegador
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CAT_Navegador()
        {
            this.NavegadorHijos = new HashSet<CAT_Navegador>();
            this.Permisos = new HashSet<CAT_PermisoUsuario>();
        }
    
        public int nRama { get; set; }
        public Nullable<int> nRamaPadre { get; set; }
        public int nOrden { get; set; }
        public string cNombreRama { get; set; }
        public string cOpcion { get; set; }
        public string cRuta { get; set; }
        public bool bActivo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CAT_Navegador> NavegadorHijos { get; set; }
        public virtual CAT_Navegador NavegadorPadre { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CAT_PermisoUsuario> Permisos { get; set; }
    }
}
