//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Back_End.ModelsBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT_Usuarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CAT_Usuarios()
        {
            this.CAP_Corte = new HashSet<CAP_Corte>();
            this.CAP_Corte1 = new HashSet<CAP_Corte>();
            this.CAP_Corte2 = new HashSet<CAP_Corte>();
            this.CAP_SolicitudPrestamo = new HashSet<CAP_SolicitudPrestamo>();
            this.CAP_SolicitudPrestamo1 = new HashSet<CAP_SolicitudPrestamo>();
            this.CAP_SolicitudPrestamo2 = new HashSet<CAP_SolicitudPrestamo>();
            this.CAT_CategoriasGasto = new HashSet<CAT_CategoriasGasto>();
            this.CAT_CategoriasGasto1 = new HashSet<CAT_CategoriasGasto>();
            this.CAT_CategoriasGasto2 = new HashSet<CAT_CategoriasGasto>();
            this.CAT_Departamentos = new HashSet<CAT_Departamentos>();
            this.CAT_Departamentos1 = new HashSet<CAT_Departamentos>();
            this.CAT_Departamentos2 = new HashSet<CAT_Departamentos>();
            this.CAT_EmpleadosArchivos = new HashSet<CAT_EmpleadosArchivos>();
            this.CAT_EmpleadosArchivos1 = new HashSet<CAT_EmpleadosArchivos>();
            this.CAT_PermisoUsuario = new HashSet<CAT_PermisoUsuario>();
            this.LOG_RecuperarPassword = new HashSet<LOG_RecuperarPassword>();
            this.LOG_Sesiones = new HashSet<LOG_Sesiones>();
        }
    
        public string cLogin { get; set; }
        public string cNombre { get; set; }
        public string cNombreCorto { get; set; }
        public string cEmail { get; set; }
        public string cPassword { get; set; }
        public System.DateTime dFechaExpiracion { get; set; }
        public int nIdRol { get; set; }
        public System.DateTime dFechaAlta { get; set; }
        public Nullable<System.DateTime> dFechaBaja { get; set; }
        public int nIntentosFallidos { get; set; }
        public System.DateTime dFechaUltimoIntento { get; set; }
        public System.DateTime dFechaBloqueo { get; set; }
        public string cFotoPerfil { get; set; }
        public bool bHombre { get; set; }
        public bool bActivo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CAP_Corte> CAP_Corte { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CAP_Corte> CAP_Corte1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CAP_Corte> CAP_Corte2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CAP_SolicitudPrestamo> CAP_SolicitudPrestamo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CAP_SolicitudPrestamo> CAP_SolicitudPrestamo1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CAP_SolicitudPrestamo> CAP_SolicitudPrestamo2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CAT_CategoriasGasto> CAT_CategoriasGasto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CAT_CategoriasGasto> CAT_CategoriasGasto1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CAT_CategoriasGasto> CAT_CategoriasGasto2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CAT_Departamentos> CAT_Departamentos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CAT_Departamentos> CAT_Departamentos1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CAT_Departamentos> CAT_Departamentos2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CAT_EmpleadosArchivos> CAT_EmpleadosArchivos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CAT_EmpleadosArchivos> CAT_EmpleadosArchivos1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CAT_PermisoUsuario> CAT_PermisoUsuario { get; set; }
        public virtual CAT_Roles CAT_Roles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOG_RecuperarPassword> LOG_RecuperarPassword { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOG_Sesiones> LOG_Sesiones { get; set; }
    }
}
