//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Back_End.ModelsBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class CFG_Configuracion
    {
        public int nIdConfig { get; set; }
        public string cNombreConfig { get; set; }
        public string cMensajeConfig { get; set; }
        public string cDetalleConfig { get; set; }
        public bool bActivo { get; set; }
        public System.DateTime dFechaRegistro { get; set; }
        public System.DateTime dFechaModificacion { get; set; }
    }
}
